-- Ties each attendance record to one assigned shift. Apply before deploying the
-- API that calls POST /attendance/checkin and /attendance/checkout with GPS data.
alter table public.attendances
  add column if not exists shift_assignment_id uuid references public.employee_shift_assignments(id) on delete set null,
  -- Idempotency keys generated by the app per tap and reused when it resends.
  add column if not exists check_in_request_id uuid,
  add column if not exists check_out_request_id uuid,
  -- IP, GPS fix and computed distance. GPS can be spoofed on the device, so
  -- this is review evidence, not proof of presence.
  add column if not exists check_in_evidence jsonb,
  add column if not exists check_out_evidence jsonb;

-- One check-in per assigned shift. When two requests race, the database keeps
-- the first insert and rejects the second with unique_violation (23505).
-- Existing rows have no shift and stay valid because NULLs never conflict.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendances'::regclass
      and conname = 'attendances_shift_assignment_id_key'
  ) then
    alter table public.attendances
      add constraint attendances_shift_assignment_id_key unique (shift_assignment_id);
  end if;
end;
$$;

-- Makes the new columns and relationship visible to PostgREST immediately.
notify pgrst, 'reload schema';
